
const { createClient } = require('@supabase/supabase-js');
require('dotenv').config();
const sb = createClient(process.env.SUPABASE_URL||process.env.VITE_SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY);
const uid = () => `b_${Date.now()}_${Math.random().toString(36).slice(2,7)}`;

const lessons = [
  {
    id: 'bbea10ea-a0aa-406a-878f-0b4536b476af',
    title: 'Definition of Iman in Qur\'an and Sunnah',
    slug: 'course-1-week-1-module-1-lesson-1',
    blocks: [
      { type:'hook', title:'The Heart That Cannot Rest', order:1, content:'A successful surgeon returns home after saving three lives. Yet lying in the dark, she feels a hollow ache she cannot name. Wealth, status, skill — none of it fills the void. This lesson begins the journey toward understanding what that void is, and what alone can fill it: Iman.' },
      { type:'bridgeFromPreviousLesson', title:'Where We Begin', order:2, content:'This is the opening lesson of the course. There is no previous lesson — but there is a previous life. You bring your doubts, your questions, your inherited beliefs. This lesson meets you exactly there and lays the first brick of conviction.' },
      { type:'learningObjectives', title:'What You Will Learn', order:3, content:'1. Define Iman according to Qur\'an and authentic Sunnah.\n2. Distinguish between Iman as declaration vs. Iman as a comprehensive state.\n3. Identify the three inseparable dimensions of faith: heart, tongue, limbs.\n4. Recognize the feedback loop between conviction and conduct.' },
      { type:'keyTerms', title:'Key Terms', order:4, content:'**Tasdiq** — Heartfelt affirmation; the heart\'s recognition and acceptance of truth.\n**Iqrar** — Verbal testimony; the public and private declaration of belief.\n**Amal** — Action by the limbs; the outward manifestation of inward conviction.\n**Iman** — The comprehensive state of faith encompassing all three above dimensions.' },
      { type:'coreTeaching', title:'What Iman Is NOT', order:5, content:'Iman is not a feeling that comes and goes with our mood. It is not a cultural identity inherited without examination. It is not a box ticked by saying words without understanding. Al-Hasan al-Basri stated: "Faith is not through outward adornment or wishful thinking — it is what settles in the heart and is proven by deeds."' },
      { type:'coreTeaching', title:'The Three-Dimensional Reality of Iman', order:6, content:'Classical scholars systematized Iman into three inseparable dimensions:\n\n**1. Tasdiq bil-Qalb** — Conviction of the heart. The heart "knows" and submits to the truth.\n**2. Iqrar bil-Lisan** — Affirmation of the tongue. The lips publicly testify.\n**3. Amal bil-Jawarih** — Action of the limbs. The body lives the belief.\n\nRemove any one dimension, and the structure weakens. A person who "believes in the heart" but never acts has a faith that has stalled.' },
      { type:'coreTeaching', title:'Iman as a Living, Breathing Reality', order:7, content:'The Qur\'an (8:2) describes true believers as those whose hearts tremble at the mention of Allah and whose faith increases upon hearing His verses. This is experiential, not merely intellectual. Faith is not a document signed once — it is a relationship maintained daily.' },
      { type:'coreTeaching', title:'The Feedback Loop: Belief ↔ Action', order:8, content:'Spiritual conviction drives ethical conduct. Ethical conduct, in turn, reinforces conviction. This is the divine feedback loop:\n\n→ You believe Allah is Al-Basir (All-Seeing)\n→ You behave with integrity even alone\n→ Acting with integrity deepens your awareness of being seen\n→ That awareness increases Iman\n\nBreaking this loop — believing without acting — produces spiritual stagnation.' },
      { type:'coreTeaching', title:'The Garment Analogy', order:9, content:'The Prophet ﷺ said: "Iman wears out in the heart of any one of you just as a garment wears out." (Al-Hakim, authenticated). Just as a worn garment needs washing, mending, and eventually replacing, Iman requires constant renewal through deliberate spiritual effort — dhikr, knowledge, good deeds, and repentance.' },
      { type:'coreTeaching', title:'Over 70 Branches of Iman', order:10, content:'The Prophet ﷺ said: "Iman has over seventy branches — or over sixty — the highest of which is to say \'La ilaha illallah\' and the lowest of which is to remove something harmful from the road. And modesty is a branch of Iman." (Muslim, 35)\n\nThis hadith demolishes the idea that faith is only a private, internal affair. Removing harm from a footpath is an act of faith.' },
      { type:'quranEvidence', title:'Qur\'anic Evidence', order:11, content:'• Surah Al-Anfal 8:2 — "The believers are only those who, when Allah is mentioned, their hearts tremble; and when His verses are recited, it increases them in faith."\n• Surah Al-Hujurat 49:15 — "The true believers are only those who have believed in Allah and His Messenger and then had no doubt."\n• Surah Al-Baqarah 2:177 — Describes true righteousness as combining belief AND action in an integrated whole.' },
      { type:'hadithEvidence', title:'Hadith Evidence', order:12, content:'• Sahih Muslim 35 — "Iman has over seventy branches; the highest is La ilaha illallah, the lowest is removing harm from a path."\n• Al-Hakim (authenticated) — "Iman wears out in the heart as garments wear out."\n• Al-Hasan al-Basri (reported in Shu\'ab al-Iman) — "Faith is not through wishful thinking; it is what settles in the heart and is proven by deeds."' },
      { type:'scholarInsight', title:'Scholar Insight', order:13, content:'**Imam al-Ghazali** (d. 1111 CE) in *Ihya Ulum al-Din* wrote that the heart is the "king" and the limbs are its subjects. When the king is corrupted (weak Iman), the kingdom descends into chaos (disordered life). When the king is sound, order flows outward naturally.\n\n**Ibn Hajar al-Asqalani** summarized the mainstream Sunni position: Iman increases with obedience and decreases with sin — confirming it is a dynamic, fluctuating state, not a fixed binary.' },
      { type:'misconceptionCorrection', title:'Common Misconception', order:14, content:'**Misconception:** "I have faith in my heart — I don\'t need to pray or act on it. God knows my intentions."\n\n**Correction:** Sincere internal belief that never produces any outward fruit contradicts the Prophetic model and classical theological consensus. The heart and limbs are connected. A heart truly \'settled\' in Iman naturally seeks expression through action. The absence of action is evidence the root is diseased, not just that the fruit is delayed.' },
      { type:'scenarioCaseStudy', title:'Case Study: The Silent Surgeon', order:15, content:'Dr. Layla is a respected cardiac surgeon. She was raised Muslim, says she "believes in God," but has not prayed in eight years. She reasoned: "My work saves lives — that\'s my worship."\n\nAfter a patient dies despite her best efforts, she feels spiritually shattered. She realizes her "belief" had no structure — no daily connection, no renewal. A colleague invites her to a class on Iman. She discovers she had the declaration (Iqrar) but the heart had drifted, and the limbs had followed.\n\n**Discussion:** What was missing from Dr. Layla\'s Iman? Which of the three dimensions had weakened? What would a "revival plan" look like?' },
      { type:'miniActivity', title:'The Iman Audit', order:16, content:'**Step 1:** On paper, draw three columns: Heart | Tongue | Limbs\n**Step 2:** Under each column, list 3 things you currently do that reflect that dimension of your faith (e.g., Tongue: you say Bismillah before eating).\n**Step 3:** Identify which column is the weakest for YOU right now.\n**Step 4:** Write one practical action you will add this week to strengthen that dimension.\n**Step 5:** Share it with one trusted person for accountability.' },
      { type:'modernApplication', title:'Faith in the Age of Anxiety', order:17, content:'Mental health professionals report a crisis of meaning in modern life. People have more information, comforts, and options than any previous generation — yet depression and anxiety are at record highs. Islamic theology offers a diagnosis: disconnection from the root of meaning. Iman in its full, three-dimensional form provides not just a belief system but a structured daily relationship with the source of existence — the very antidote to existential emptiness.' },
      { type:'modernApplication', title:'Iman in the Digital Age', order:18, content:'Social media has created a culture of performed identity. People display religiosity (Iqrar) without the inner reality (Tasdiq). This is the modern equivalent of the garment with no fabric — all display, no substance. Reclaiming Iman in the digital age means intentionally building the private, unseen dimensions of faith: secret worship, private dhikr, anonymous charity. These are the roots that hold when public storms arrive.' },
      { type:'checkpointQuiz', title:'Checkpoint Quiz', order:19, content:'**Q1:** According to Al-Hasan al-Basri, what is true Iman?\na) Saying the Shahada publicly\nb) What settles in the heart and is proven by action ✓\nc) Performing Hajj\nd) Having strong emotions during worship\n\n**Q2:** Which Surah and verse describes believers whose hearts tremble at the mention of Allah?\na) Al-Baqarah 2:1\nb) Al-Anfal 8:2 ✓\nc) Al-Hujurat 49:14\nd) Al-Ikhlas 112:1\n\n**Q3:** Which of these is NOT one of the three dimensions of Iman?\na) Tasdiq (heart)\nb) Iqrar (tongue)\nc) Tafakkur (reflection) ✓\nd) Amal (action)\n\n**Q4:** The hadith about Iman having "over 70 branches" is found in:\na) Sahih Bukhari\nb) Sahih Muslim ✓\nc) Sunan Ibn Majah\nd) Muwatta Malik\n\n**Q5:** What does the "garment" analogy for Iman teach us?\na) Iman looks different on everyone\nb) Iman wears out and needs constant renewal ✓\nc) Iman is inherited from parents\nd) Iman is only for scholars' },
      { type:'shortAnswer', title:'Short Answer Questions', order:20, content:'**SAQ1:** Explain the feedback loop between Iman and action. Use a concrete example from daily life.\n*Marking: 1 point for identifying belief drives action; 1 point for showing how action reinforces belief; 1 point for a relevant example.*\n\n**SAQ2:** Why is the "over 70 branches" hadith significant for understanding the scope of Iman?\n*Marking: 1 point for showing Iman includes social acts; 1 point for identifying that both major acts (Shahada) and minor acts (removing harm) count as Iman.*' },
      { type:'guidedReflection', title:'Guided Reflection', order:21, content:'Think of a moment in your life when your faith felt most alive — when Iman was not just a word but a felt reality.\n\n• What were you doing?\n• Who were you with?\n• What had you been feeding your heart in the days before?\n\nNow think about your life right now. What has changed? What are the gaps? Write 5 sentences about what "reviving that feeling" would look like in practical terms this week.' },
      { type:'actionPlan', title:'Your 7-Day Iman Action Plan', order:22, content:'**Day 1:** Audit your schedule — identify 3 existing actions that testify to your faith.\n**Day 2:** Select one Prophetic habit (e.g., saying Bismillah, smiling at others, removing litter) and commit to it all day.\n**Day 3:** Read Surah Al-Anfal 8:2 and sit with it for 5 minutes in silence.\n**Day 4:** Perform one "invisible" act of worship — no one knows except Allah.\n**Day 5:** Review the three dimensions: which needs most work this week?\n**Day 6:** Tell one person something true about their worth — act from Iman.\n**Day 7:** Renew your Niyyah (intention) before every single action.' },
      { type:'dua', title:'Du\'a for Firm Faith', order:23, content:'**Arabic:** يَا مُقَلِّبَ الْقُلُوبِ ثَبِّتْ قَلْبِي عَلَى دِينِكَ\n**Transliteration:** Ya Muqallib al-Qulub, thabbit qalbi \'ala dinik\n**Translation:** "O Turner of Hearts, keep my heart firm upon Your religion."\n**Source:** Tirmidhi 3522, authenticated. The Prophet ﷺ recited this abundantly.' },
      { type:'youtubeRecommendedLecture', title:'Recommended Lecture', order:24, content:'**Topic:** The Beauty of Faith — What is Iman?\n**Channel:** Yaqeen Institute for Islamic Research\n**URL:** https://www.youtube.com/watch?v=m1RqRgFBrxI\n**Why this lecture:** Dr. Omar Suleiman walks through the lived experience of Iman, connecting the classical definition to emotional and spiritual reality.' },
      { type:'summary', title:'Lesson Summary', order:25, content:'• Iman is not a feeling or a label — it is a three-dimensional reality: heart, tongue, and limbs.\n• Al-Hasan al-Basri: true faith settles in the heart AND is proven by deeds.\n• Iman is dynamic — it increases with obedience and decreases with neglect.\n• The garment analogy: faith wears out and must be actively renewed.\n• Even removing harm from a path is a branch of Iman — faith has social dimensions.\n• The feedback loop: conviction → action → deeper conviction.' },
      { type:'resources', title:'Resources & Verification Links', order:26, content:'1. Yaqeen Institute — Faith Revival Series: https://yaqeeninstitute.org/series/faith-revival\n2. SeekersGuidance — What Is Iman?: https://seekersguidance.org/answers/aqeedah-creed/what-is-the-reality-of-iman-and-how-can-i-truly-be-a-mumin/\n3. Sahih Muslim 35 (70 branches): https://sunnah.com/muslim:35\n4. Al-Hafiz Ibn Hajar — Fath al-Bari (commentary on Iman chapters): Available via Islamic heritage libraries.\n5. Quran 8:2 — https://quran.com/8/2\n6. Quran 49:15 — https://quran.com/49/15\n7. SeekersGuidance — Is depression a sign of weak faith?: https://seekersguidance.org/answers/is-depression-a-sign-of-weak-faith/' }
    ]
  },
  {
    id: '38d0e417-bd08-4eba-87d6-d05c0a3df97a',
    title: 'Linguistic vs Technical Meaning of Faith',
    blocks: [
      { type:'hook', title:'The Word That Builds Civilizations', order:1, content:'The Arabic root a-m-n (أ م ن) gave the world the word "Amin" — safety, security, trustworthiness. The same root gave us "Iman." Before a single prayer is discussed, this lesson asks: do you truly feel safe? Because the linguistic promise of this faith is that you can.' },
      { type:'bridgeFromPreviousLesson', title:'Building on Lesson 1', order:2, content:'Last lesson established that Iman is a three-dimensional reality: heart, tongue, and limbs. Now we go one level deeper — into the actual word "Iman." What does it mean at its linguistic root? And how does the technical (Shari\'i) definition expand that root? The gap between these two tells us why so many people "know about" their faith but don\'t feel it.' },
      { type:'learningObjectives', title:'What You Will Learn', order:3, content:'1. Trace the linguistic root of Iman to its core meaning of security and safety.\n2. Define the technical (Shari\'i) meaning of Iman as belief in the Prophet\'s message.\n3. Explain why both meanings must coexist for faith to be functional.\n4. Apply the "Amn" framework as a spiritual tool for managing modern anxiety.' },
      { type:'keyTerms', title:'Key Terms', order:4, content:'**Amn (أَمْن)** — Safety, security, the absence of fear; the linguistic root of Iman.\n**Iman (إِيمَان)** — Technical: believing in Allah, His angels, books, messengers, the Last Day, and Divine Decree.\n**Lughawi** — Linguistic/etymological meaning of a term.\n**Shar\'i / Istilahi** — Technical or legal meaning as defined by Islamic scholarship.' },
      { type:'coreTeaching', title:'The Root: A-M-N', order:5, content:'The Arabic root أ-م-ن (A-M-N) generates a family of words that share a core meaning:\n\n• **Amn** — Security, safety\n• **Amanah** — Trust, something held in safekeeping\n• **Amin** — Trustworthy one (a title given to the Prophet ﷺ before prophethood)\n• **Iman** — The state of having granted security/trust to a truth\n\nTo "have Iman" in something is to grant it your full interior trust — to place your security in it.' },
      { type:'coreTeaching', title:'The Linguistic Gift: Iman as Inner Peace', order:6, content:'When you truly trust in Allah — His plan, His mercy, His control — fear loses its grip. The Qur\'an (106:4) praises Allah as the One who "fed them against hunger AND made them safe (amana-hum) from fear." Security and sustenance are paired because both come from the same source.\n\nA believer who understands the root of Iman knows that faith is not primarily a set of rules — it is a state of interior security that rules then flow from.' },
      { type:'coreTeaching', title:'The Technical Definition', order:7, content:'Technically, Iman is defined by Islamic scholars as: "Believing in Allah, His angels, His books, His messengers, the Last Day, and divine decree — both the good of it and the bad of it." (Derived from the Hadith of Jibreel, Sahih Muslim 8)\n\nImam al-Jurjani defined it as: "The acknowledgment of the heart and the affirmation of the tongue of the truth of the Prophetic message."\n\nThis technical definition is precise, testable, and complete. It maps exactly to the six pillars of Iman studied in Module 2.' },
      { type:'coreTeaching', title:'When Linguistic and Technical Diverge', order:8, content:'A person may have the linguistic experience (Amn — a vague sense of peace or spiritual connection) without the technical content (correct belief in the six pillars). This produces a spirituality that feels good but lacks structure — what researchers call "believing without belonging."\n\nConversely, a person may hold technical Iman (all the correct doctrines memorized) without the linguistic experience (no felt peace, no sense of security). This produces rigidity, anxiety, and a harsh relationship with religion.\n\n**True Iman requires both.** The technical defines WHAT we believe; the linguistic transforms HOW that belief feels.' },
      { type:'coreTeaching', title:'The Combination: Certainty + Security', order:9, content:'Imam al-Nawawi noted that Iman\'s full richness emerges when a person has both:\n\n1. **Yaqeen** (certainty) — the technical correctness of belief\n2. **Amn** (security) — the felt realization that you are held, protected, and guided\n\nWithout certainty, security becomes superstition. Without security, certainty becomes mere academia. Together, they produce the believer who is intellectually grounded AND emotionally settled.' },
      { type:'coreTeaching', title:'The Prophet\'s Name: Al-Amin', order:10, content:'Before the first revelation, Quraysh unanimously called Muhammad ﷺ "Al-Amin" — the Trustworthy. This name came from the same root: A-M-N. The community recognized in him a man in whom you could place your ultimate trust — your valuables, your secrets, your life.\n\nThis is the model of the believer: someone in whose presence others feel safe, because they carry within them the security (Amn) that flows from genuine faith (Iman).' },
      { type:'quranEvidence', title:'Qur\'anic Evidence', order:11, content:'• Surah Quraysh 106:4 — "Who fed them against hunger and made them safe (amanahu) from fear." — Security as a divine gift.\n• Surah Al-Baqarah 2:285 — The Messenger believes in what was revealed; the verse lists technical content of belief (Allah, angels, books, messengers).\n• Surah Al-Ra\'d 13:28 — "Verily, in the remembrance of Allah do hearts find rest (tatma\'inn)." — The linguistic promise of Amn fulfilled through dhikr.' },
      { type:'hadithEvidence', title:'Hadith Evidence', order:12, content:'• Sahih Muslim 8 (Hadith of Jibreel) — Technical definition of Iman: "Believe in Allah, His angels, His books, His messengers, the Last Day, and divine decree."\n• Bukhari 6 — The Prophet ﷺ was known as Al-Amin (The Trustworthy) — demonstrating the lived reality of the A-M-N root.\n• Tirmidhi 2518 — "How wonderful is the affair of the believer, for all of it is good. If good comes, he is thankful; if harm comes, he is patient." — Security (Amn) expressed through equanimity.' },
      { type:'scholarInsight', title:'Scholar Insight', order:13, content:'**Imam al-Jurjani** (*al-Ta\'rifat*, d. 1413 CE): Defined Iman technically as "the acknowledgment by the heart and affirmation by the tongue of the truth of the Prophetic message." He insisted both elements are essential — heart alone is insufficient; tongue alone is hypocrisy.\n\n**SeekersGuidance scholars** note that understanding the linguistic root of Iman is the gateway to experiencing faith as protection rather than obligation — a paradigm shift that revolutionizes the spiritual life of adult learners who grew up with a fear-based relationship to religion.' },
      { type:'misconceptionCorrection', title:'Common Misconception', order:14, content:'**Misconception:** "I can be a good person and have a spiritual connection to God without following the technical details of Islamic belief."\n\n**Correction:** The linguistic Amn (inner peace, trust) is real and valuable — but it is also fragile and easily misled without the technical anchor of revelation. History shows that sincere hearts without prophetic guidance drift into superstition, innovation, or moral relativism. The technical definition is not bureaucracy; it is the map that helps your inner compass remain calibrated.' },
      { type:'scenarioCaseStudy', title:'Case Study: Two Brothers', order:15, content:'**Hamid** memorized all six pillars of Iman and can answer any question about theology. But he is chronically anxious, rigid with his family, and feels no joy in worship. He has the technical — but not the linguistic experience of safety.\n\n**Tariq** feels deeply connected to God, finds nature spiritual, prays occasionally, but has never studied the six pillars systematically. He is warm and peaceful — but recently read an article questioning prophethood and found he had no intellectual anchor.\n\n**Discussion:** What does each brother have? What is each missing? How would you design a 30-day plan to help each one toward complete Iman?' },
      { type:'miniActivity', title:'The Safety Audit', order:16, content:'**Step 1:** Write down three things in your life you currently find emotionally "safe" — people, places, income sources, habits.\n**Step 2:** For each, ask: "What if this disappeared overnight?"\n**Step 3:** Rate your internal security level (1–10) when imagining losing each.\n**Step 4:** Now ask: "If my Iman (Amn = security from Allah) were fully activated, how would my number change?"\n**Step 5:** Write one sentence about what your life would feel like if you truly internalized: "My security comes from Allah — not from any of these."' },
      { type:'modernApplication', title:'Iman as the Answer to Modern Anxiety', order:17, content:'A 2022 global poll found that 74% of adults under 35 reported feeling "overwhelmed" by uncertainty. The modern world constantly signals: "You are not safe unless you have enough money, status, followers, or insurance."\n\nThe linguistic root of Iman directly confronts this. It says: there is a different source of safety — one that cannot be taken by a market crash, a health diagnosis, or a social media comment. This is not escapism; it is the deepest psychological reorientation possible: moving from conditional security to unconditional Amn.' },
      { type:'modernApplication', title:'Rebuilding the Technical Foundation', order:18, content:'Many adult Muslims raised in Muslim-majority cultures absorbed Islam culturally without ever deliberately learning its technical doctrines. When doubts arrive (as they do in university, through social media, or in crisis), there is no intellectual structure to return to.\n\nThis lesson argues that learning the technical definition of Iman is not dry theology — it is building the fortress walls before the storm arrives. Combine it with the lived experience of Amn, and you have both the structure and the lived reality of a resilient faith.' },
      { type:'checkpointQuiz', title:'Checkpoint Quiz', order:19, content:'**Q1:** What is the linguistic root of the word Iman?\na) I-M-N\nb) A-M-N ✓\nc) A-L-M\nd) I-L-H\n\n**Q2:** What does "Amn" primarily mean?\na) Obedience\nb) Prayer\nc) Safety, security, absence of fear ✓\nd) Knowledge\n\n**Q3:** According to Imam al-Jurjani, what constitutes Iman?\na) Prayer and fasting\nb) Acknowledgment of the heart AND affirmation of the tongue ✓\nc) Feeling spiritual\nd) Following cultural traditions\n\n**Q4:** Why was the Prophet ﷺ called "Al-Amin"?\na) He was the youngest in his family\nb) He memorized the most Qur\'an\nc) He was uniquely trustworthy — the community placed full confidence in him ✓\nd) He was the fastest runner in Makkah\n\n**Q5:** What happens when a person has technical Iman without the linguistic experience (Amn)?\na) They become more charitable\nb) They become rigid and feel no peace, anxiety persists ✓\nc) They earn more reward\nd) Nothing — technical Iman is sufficient alone' },
      { type:'shortAnswer', title:'Short Answer Questions', order:20, content:'**SAQ1:** Explain why both the linguistic and technical meanings of Iman must coexist. Use the example of "Hamid and Tariq" from the case study.\n*Marking: 1pt for linguistic = inner peace; 1pt for technical = correct belief anchor; 1pt for showing the danger of having only one.*\n\n**SAQ2:** How does understanding the root "Amn" change your practical relationship to worry or anxiety?\n*Marking: 1pt for connecting Amn to divine security; 1pt for showing how this affects emotional response to uncertainty; 1pt for a practical application.*' },
      { type:'guidedReflection', title:'Guided Reflection', order:21, content:'Sit quietly for 5 minutes. Ask \nyourself:\n\n"Where do I currently place my security? What makes me feel \\\'safe\\\'?"\n\nHonestly list three sources: a \nsavings account, a relationship, a career.\n\nThen slowly read Surah Al-Ra\\\'d 13:28: *"Verily, in the remembrance of \nAllah do hearts find rest."*\n\nWrite: What would it feel like to make Allah the PRIMARY source of your Amn — not a \nbackup plan, but the foundation? What would change in your choices this week?' },
      { type:'actionPlan', title:'Your Linguistic Iman Action Plan', order:22, content:'**Step 1:** Memorize the root A-M-N and its three derivatives (Amn, Amanah, Iman).\n**Step 2:** Each morning, say: "My security is from Allah" before checking your phone.\n**Step 3:** Study the six pillars of Iman (technical definition) — write them on paper tonight.\n**Step 4:** Identify one area of life where you seek security from something other than Allah — and consciously redirect that seeking to Him through du\'a.\n**Step 5:** Before bed, note one moment today where you felt genuine Amn — trace it back to its source.' },
      { type:'dua', title:'Du\'a for Security and Certainty', order:23, content:'**Arabic:** اللَّهُمَّ إِنِّي أَسْأَلُكَ الْيَقِينَ وَالْعَافِيَةَ\n**Transliteration:** Allahumma inni as\'aluka al-yaqeena wal-\'afiyah\n**Translation:** "O Allah, I ask You for certainty (in faith) and wellbeing."\n**Source:** Reported in Musnad Ahmad and authenticated. Ibn Mas\'ud said: "After certainty of faith, I ask for nothing greater than wellbeing."' },
      { type:'youtubeRecommendedLecture', title:'Recommended Lecture', order:24, content:'**Topic:** Linguistic Depths of Iman — Security in the Name\n**Channel:** Bayyinah Institute / Nouman Ali Khan\n**URL:** https://www.youtube.com/watch?v=F8TKK4-oe8I\n**Why this lecture:** Nouman Ali Khan is renowned for unpacking Arabic roots in a way that transforms how learners experience Qur\'anic vocabulary.' },
      { type:'summary', title:'Lesson Summary', order:25, content:'• Iman comes from A-M-N: safety, security, trust — it is not just a belief system but a state of being.\n• Technical Iman: believing in the six pillars from the Hadith of Jibreel.\n• Linguistic Iman: the lived experience of divine security (Amn).\n• Both must coexist: technical without linguistic = rigidity; linguistic without technical = fragility.\n• The Prophet ﷺ was called Al-Amin because he embodied this security for others.\n• Modern anxiety is answered by transferring primary security from worldly sources to Allah.' },
      { type:'resources', title:'Resources & Verification Links', order:26, content:'1. SeekersGuidance — Reality of Iman: https://seekersguidance.org/answers/aqeedah-creed/what-is-the-reality-of-iman-and-how-can-i-truly-be-a-mumin/\n2. Yaqeen Institute — Guidebook to God Series: https://yaqeeninstitute.org/series/guidebook-to-god\n3. Sahih Muslim 8 (Hadith of Jibreel): https://sunnah.com/muslim:8\n4. Quran 13:28: https://quran.com/13/28\n5. Quran 106:4: https://quran.com/106/4\n6. Tirmidhi 2518: https://sunnah.com/tirmidhi:2518\n7. Bayyinah — Arabic root studies: https://bayyinah.com' }
    ]
  },
  {
    id: '7b2c7cfe-bfc7-4d82-a42a-f236207d4fb7',
    title: 'Relationship Between Belief and Action',
    blocks: [
      { type:'hook', title:'The Tree That Never Grew', order:1, content:'A man plants a seed, waters it once, then walks away — returning years later to find bare earth. "The seed was good," he insists. "I believed in it." But a seed needs consistent care to become a tree. Faith is the same. The conviction may be genuine. But if it never breaks the surface of your actions, it starves itself of the sunlight it needs to grow.' },
      { type:'bridgeFromPreviousLesson', title:'Building on Lesson 2', order:2, content:'We have now established WHAT Iman is (three dimensions) and WHERE it comes from (the A-M-N root). Now we ask the most practical question: Once you have Iman in your heart, what does it DO? This lesson maps the relationship between internal belief and outward action — the organic link that classical scholars called inseparable.' },
      { type:'learningObjectives', title:'What You Will Learn', order:3, content:'1. Explain the "tree" model of the relationship between belief and deed.\n2. Analyze hadiths that directly link Iman to social and ethical conduct.\n3. Identify specific "social branches" of faith that most modern Muslims overlook.\n4. Build a personal "faith-to-action" map using the 99 Names of Allah.' },
      { type:'keyTerms', title:'Key Terms', order:4, content:'**Amal Salih** — Righteous deeds; the external manifestation of internal faith.\n**Niyyah** — Intention; the engine that transforms an ordinary act into an act of worship.\n**Khushu** — Focused presence and humility; the inner quality that elevates outward action.\n**Sila** — Connection; used here for the organic connection between belief and deed.' },
      { type:'coreTeaching', title:'The Tree Model: Roots, Trunk, Fruit', order:5, content:'The Qur\'an itself uses the tree metaphor (14:24): "A good word is like a good tree — its root is firm and its branch is in the sky, producing fruit every season by permission of its Lord."\n\nClassical scholars mapped this to faith:\n\n• **Roots** = Inward belief (Iman in the heart)\n• **Trunk/branches** = Character and ritual worship\n• **Fruit** = Benefit to self and society\n\nA rootless tree cannot stand in a storm. A tree with no fruit has missed its purpose.' },
      { type:'coreTeaching', title:'The Prophetic Linkage of Faith to Ethics', order:6, content:'The Prophet ﷺ repeatedly framed social and ethical actions as requirements of faith:\n\n• "Let whoever believes in Allah and the Last Day speak good or remain silent." (Bukhari, Muslim)\n• "Let whoever believes in Allah and the Last Day honor his neighbor." (Bukhari)\n• "Let whoever believes in Allah and the Last Day honor his guest." (Bukhari)\n\nNotice the formula: **believing in Allah + the Last Day → specific social conduct.** The Prophet did not say "it would be nice" — he said it is what belief in Allah demands.' },
      { type:'coreTeaching', title:'Character IS the Test of Faith', order:7, content:'The Prophet ﷺ said: "The most complete of believers in faith are those with the best character." (Abu Dawud 4682, authenticated by al-Albani)\n\nThis is one of the most overlooked hadith in popular religiosity. We often measure Iman by ritual intensity (how long the prayer is, how loud the dhikr). But the Prophet measured it by character quality. A person with shorter prayers but excellent character may have "more complete" Iman than a long-prayer person with terrible treatment of people.' },
      { type:'coreTeaching', title:'The Names of Allah Bridge', order:8, content:'Every Name of Allah implies a corresponding divine value. Since the believer is trying to reflect the Divine, each Name should generate a particular behavior:\n\n• **Al-Karim** (The Generous) → The believer is generous\n• **Al-Adl** (The Just) → The believer is fair and just\n• **Al-Rahim** (The Merciful) → The believer shows mercy\n• **Al-Halim** (The Forbearing) → The believer is patient\n\nThis "Names-to-Values-to-Actions" pathway is one of the most powerful practical tools in Islamic spirituality.' },
      { type:'coreTeaching', title:'When Action Is Missing: The Dead Heart', order:9, content:'Ibn al-Qayyim described the heart in three states:\n\n1. **Living heart** — Responds to truth, generates action, feels Khushu\n2. **Sick heart** — Oscillates between truth and desire, inconsistent action\n3. **Dead heart** — No response to truth; action absent or purely performative\n\nThe absence of any action from a person who claims Iman is a diagnostic sign — not of certain disbelief — but of a heart that requires urgent spiritual attention.' },
      { type:'coreTeaching', title:'Niyyah: The Converter', order:10, content:'The Prophet ﷺ said: "Actions are only by intentions, and every person gets only what they intended." (Bukhari 1, Muslim 1907)\n\nNiyyah (intention) is the engine that converts an ordinary action into an act of worship. Driving to work can become an act of Iman if the Niyyah is to provide for your family in obedience to Allah. Eating can become worship with the right intention.\n\nThis means the connection between belief and action is not just about what you DO — but WHY.' },
      { type:'quranEvidence', title:'Qur\'anic Evidence', order:11, content:'• Surah Ibrahim 14:24-25 — "The good word is like a good tree — root firm, branches in the sky, giving fruit every season."\n• Surah Al-Asr 103:1-3 — "By time! Indeed man is in loss — EXCEPT those who have believed AND done righteous deeds." Belief and action paired in the Oath of Time.\n• Surah Al-Baqarah 2:177 — Extended definition of righteousness integrating belief (in Allah, angels, books, messengers, Last Day) AND action (charity, prayer, keeping promises).' },
      { type:'hadithEvidence', title:'Hadith Evidence', order:12, content:'• Bukhari 6018, Muslim 47 — "Let whoever believes in Allah and Last Day speak good or be silent; honor neighbor; honor guest."\n• Abu Dawud 4682 — "Most complete in faith are those with best character."\n• Muslim 35 — "Iman has 70+ branches — including removing harm from the road."\n• Bukhari 1, Muslim 1907 — "Actions are by intentions." The engine that links belief to action.' },
      { type:'scholarInsight', title:'Scholar Insight', order:13, content:'**Ibn al-Qayyim al-Jawziyyah** (*Madarij al-Salikin*): "The heart is the king and the limbs are its army. When the king is righteous, the army becomes righteous. When the king is corrupt, the army becomes corrupt. Yet no one questions the king — only the army is visible." This explains why surface-level behavior change without heart-work fails permanently.\n\n**Imam al-Ghazali** (*Ihya Ulum al-Din*): Actions without inward conviction are "husks without grain." But equally, conviction without action is grain that the farmer never planted.' },
      { type:'misconceptionCorrection', title:'Common Misconception', order:14, content:'**Misconception:** "Belief and action are separate. I can have strong faith in my heart even if my actions are poor. Allah knows my heart."\n\n**Correction:** Allah does know the heart — and that is exactly why He knows whether the faith is genuine. The prophetic formula ("whoever believes in Allah AND the Last Day → acts") is not a suggestion. The organic link between root and fruit is not optional — it is biological. A root disconnected from its fruit is dead. The test of the root\'s health is the fruit it eventually produces.' },
      { type:'scenarioCaseStudy', title:'Case Study: The Angry Engineer', order:15, content:'**Kareem** is a devout-seeming Muslim: he prays five times, fasts Ramadan, and recites Qur\'an daily. However, he is chronically harsh with his employees, never returns favors, and treats his family with cold efficiency.\n\nA colleague invites him to a study circle on the Names of Allah. He begins studying Al-Halim (The Forbearing). Something shifts. He realizes his worship is disconnected from his character — the branches exist, but they produce sour fruit.\n\n**Reflection questions:**\n1. What does Kareem\'s situation tell us about ritual worship without character development?\n2. Which hadith directly addresses his case?\n3. Design a 2-week "Character Audit" for Kareem using the Names of Allah bridge.' },
      { type:'miniActivity', title:'The Character Map', order:16, content:'**Instructions:**\n\n**Step 1:** Choose 3 character traits you want to embody more fully (e.g., generosity, patience, honesty).\n\n**Step 2:** Find the Name of Allah that corresponds to each trait:\n• Generosity → Al-Karim\n• Patience → Al-Halim / Al-Sabur\n• Honesty → Al-Haqq\n\n**Step 3:** For each Name, write one concrete action you will take this week that reflects that attribute.\n\n**Step 4:** Set a daily 2-minute reminder to check: "Did I act on this today?"' },
      { type:'modernApplication', title:'The Workplace as a Worship Space', order:17, content:'The modern separation of "religious life" and "professional life" has no basis in Islamic thought. Every workplace interaction — how you treat a junior colleague, whether you return borrowed items, how you give feedback — is either building or eroding your Iman.\n\nThe hadith "honor your neighbor" extends to your desk neighbor, your Zoom colleague, your client. Reclaiming Iman in the modern world means treating professional ethics as an expression of faith, not as a separate secular concern.' },
      { type:'modernApplication', title:'Social Media and the Niyyah Test', order:18, content:'Every post, comment, and share can be tested against Niyyah: "Why am I sharing this?" If the answer is "to look religious" — this violates Ikhlas (sincerity). If the answer is "to benefit someone who needs this" — this is a branch of Iman.\n\nThe Prophetic standard "speak good or remain silent" is directly applicable to our digital feeds. Scrolling, posting, and reacting are all actions — and all actions fall under the domain of Iman or its absence.' },
      { type:'checkpointQuiz', title:'Checkpoint Quiz', order:19, content:'**Q1:** Which Surah and verse uses the tree metaphor for faith and good speech?\na) Al-Ikhlas 112:1\nb) Ibrahim 14:24 ✓\nc) Al-Anfal 8:2\nd) Al-Asr 103:2\n\n**Q2:** According to Abu Dawud 4682, who is "most complete in faith"?\na) Those who pray the longest\nb) Those who fast the most\nc) Those with the best character ✓\nd) Those who give the most charity\n\n**Q3:** What is Niyyah and why does it matter for this lesson?\na) A type of prayer\nb) The intention that converts action into worship ✓\nc) A scholarly title\nd) The direction of prayer\n\n**Q4:** Which of these is a direct Prophetic formula linking belief to social action?\na) "Pray much and fast much"\nb) "Whoever believes in Allah and the Last Day, let him honor his neighbor" ✓\nc) "The best worship is reading Qur\'an"\nd) "Learn Arabic before everything else"\n\n**Q5:** According to Ibn al-Qayyim, what is the "king" in the heart-limbs model?\na) The tongue\nb) The limbs\nc) The heart ✓\nd) The intellect' },
      { type:'shortAnswer', title:'Short Answer Questions', order:20, content:'**SAQ1:** Using the tree metaphor and one supporting hadith, explain why good character is a requirement of Iman — not just a bonus.\n*Marking: 1pt for identifying roots = faith, fruit = character; 1pt for citing Abu Dawud 4682 or equivalent; 1pt for explaining the organic necessity.*\n\n**SAQ2:** A student says: "I have strong faith, but I struggle with telling the truth at work. These are separate issues." Respond using the prophetic formula for the relationship between Iman and action.\n*Marking: 1pt for citing honesty as a branch of Iman; 1pt for referencing the "believe and speak good or be silent" formula; 1pt for practical application.*' },
      { type:'guidedReflection', title:'Guided Reflection', order:21, content:'Think of one character trait you know needs work — one place where your inner standard (what you believe is right) and your outer behavior (what you actually do) are misaligned.\n\n• What specific situation triggers this misalignment?\n• What Name of Allah corresponds to the virtue you are aspiring toward?\n• What ONE small action would begin to close the gap between your belief and your behavior today?\n\nWrite your answer as a private commitment: "I believe that Allah is [Name]. Therefore, I will [action]."' },
      { type:'actionPlan', title:'Faith-to-Action Plan', order:22, content:'**Step 1:** Print or write the 99 Names of Allah — identify your top 5 favorites.\n**Step 2:** For each Name, write the character trait it implies for YOU.\n**Step 3:** Design 5 "faith-to-action" sentences: "Because I believe in Allah as [Name], I will [specific behavior] this week."\n**Step 4:** Check one off per day over the next 5 days.\n**Step 5:** At the end of 5 days, write: "Which action felt most natural? Which felt hardest?" — this reveals your current spiritual strengths and gaps.' },
      { type:'dua', title:'Du\'a for Righteous Character', order:23, content:'**Arabic:** اللَّهُمَّ أَحْسَنْتَ خَلْقِي فَأَحْسِنْ خُلُقِي\n**Transliteration:** Allahumma ahsanta khalqi fa-ahsin khuluqi\n**Translation:** "O Allah, You have made my physical form good, so make my character good."\n**Source:** Reported in Musnad Ahmad and Ibn Hibban, authenticated. Recited by the Prophet ﷺ himself as a supplication for character excellence.' },
      { type:'youtubeRecommendedLecture', title:'Recommended Lecture', order:24, content:'**Topic:** Faith and Character — The Inseparable Pair\n**Channel:** Yaqeen Institute for Islamic Research\n**URL:** https://www.youtube.com/watch?v=m1RqRgFBrxI\n**Why this lecture:** This session explores the prophetic synthesis of belief and character, showing how the companions\' lives demonstrate the faith-to-action pipeline in practice.' },
      { type:'summary', title:'Lesson Summary', order:25, content:'• Belief and action are organically connected — the tree model: roots (faith), branches (worship), fruit (character and social service).\n• The Prophet repeatedly framed ethical social behavior as a direct requirement of believing in Allah and the Last Day.\n• "Most complete in faith are those with the best character" — character is the measure of faith maturity.\n• Niyyah (intention) is the converter that transforms any action into an act of worship.\n• Ibn al-Qayyim: the heart is king — when it is right, life is right.\n• The test of your Iman today: how do you treat the people closest to you?' },
      { type:'resources', title:'Resources & Verification Links', order:26, content:'1. Yaqeen — Character in the Prophetic Model: https://yaqeeninstitute.org/read/paper/the-morality-toolkit\n2. SeekersGuidance — Faith and Deeds: https://seekersguidance.org\n3. Quran 14:24-25: https://quran.com/14/24\n4. Quran 103:1-3: https://quran.com/103\n5. Abu Dawud 4682: https://sunnah.com/abudawud:4682\n6. Bukhari 6018: https://sunnah.com/bukhari:6018\n7. Ibn al-Qayyim — Madarij al-Salikin (translated excerpts available at SunniPath.com)' }
    ]
  }
];

async function seedLessons() {
  console.log('\n============================================');
  console.log('SEEDING MODULE 1 — Lessons 1, 2, 3');
  console.log('Block structure: Exact 23-26 blocks per lesson');
  console.log('============================================\n');

  for (const lesson of lessons) {
    process.stdout.write(`📖 Seeding "${lesson.title}"... `);
    const finalBlocks = lesson.blocks.map(b => ({ ...b, id: uid() }));
    const { error } = await sb.from('course_lessons')
      .update({ content_blocks: finalBlocks, duration_minutes: 45 })
      .eq('id', lesson.id);
    if (error) console.log(`❌ ${error.message}`);
    else console.log(`✅ ${finalBlocks.length} blocks`);
  }

  console.log('\n✅ MODULE 1 PARTIAL SEED COMPLETE (Lessons 1-3)');
  console.log('Run SEED_W1_MOD1_B.js for Lessons 4-7\n');
}

seedLessons().catch(e => { console.error('Fatal:', e); process.exit(1); });
