/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Workflow Brand Colors
        'accent': '#0046FF', // Standardized to Blue
        'sapphire': '#0046FF',
        'ink': '#0A1324',
        'ink-light': '#1e293b',
        'accent-50': '#F5F9FF',
        'accent-100': '#E6F0FF',
        'accent-200': '#CCE0FF',
        'accent-300': '#B3D1FF',
        'accent-400': '#99C2FF',
        'accent-500': '#80B3FF',
        'accent-600': '#66A4FF',
        'accent-700': '#4D95FF',
        'accent-800': '#3386FF',
        'accent-900': '#1A77FF',
        'workflow-primary': '#0046FF',
        'workflow-primary-50': '#F5F9FF',
        'workflow-primary-100': '#E6F0FF',
        'workflow-primary-200': '#CCE0FF',
        'workflow-primary-300': '#B3D1FF',
        'workflow-primary-400': '#99C2FF',
        'workflow-primary-500': '#80B3FF',
        'workflow-primary-600': '#0038CC', // Darker shade for hover
        'workflow-primary-700': '#4D95FF',
        'workflow-primary-800': '#3386FF',
        'workflow-primary-900': '#1A77FF',
        'workflow-accent': '#8B5CF6',
        'white': '#FFFFFF',
        'private': 'rgb(var(--color-bg-rgb) / <alpha-value>)',
        // Primary Theme Colors (Linked to CSS Variables)
        'bg': 'rgb(var(--color-bg-rgb) / <alpha-value>)',
        'surface': 'rgb(var(--color-surface-rgb) / <alpha-value>)',
        'surface-elevated': 'rgb(var(--color-surface-elevated-rgb) / <alpha-value>)',
        'border': 'rgb(var(--color-border-rgb) / <alpha-value>)',
        'text-primary': 'var(--color-text)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-muted': 'var(--color-text-muted)',
        // Dark mode colors
        'dark': {
          'bg': 'rgb(var(--color-bg-rgb) / <alpha-value>)',
          'surface': 'rgb(var(--color-surface-rgb) / <alpha-value>)',
          'surface-elevated': 'rgb(var(--color-surface-elevated-rgb) / <alpha-value>)',
          'border': 'var(--color-border)',
          'text': 'var(--color-text)',
          'text-secondary': 'var(--color-text-secondary)',
          'text-muted': 'var(--color-text-muted)',
          'accent': 'var(--workflow-primary)',
        },
        'success': {
          '50': '#F0F7FF',
          '100': '#E0EFFF',
          '500': '#0046FF',
          '600': '#0038CC',
        },
        'error': {
          '50': '#F9FAFB',
          '100': '#F3F4F6',
          '500': '#0F172A',
          '600': '#030712',
        },
        'warning': {
          '50': '#FFFFFF',
          '100': '#E2E8F0',
          '500': '#64748B',
          '600': '#475569',
        },
        'secondary': {
          '100': '#F1F5F9',
          '200': '#E2E8F0',
          '300': '#CBD5E1',
          '400': '#94A3B8',
          '500': '#64748B',
          '600': '#475569',
        },
        // Global Theme Variables (Internal Mappings)
        'bg-bg': 'rgb(var(--color-bg-rgb) / <alpha-value>)',
        'bg-elevated': 'rgb(var(--color-surface-elevated-rgb) / <alpha-value>)',
        'border-primary': 'rgb(var(--color-border-rgb) / <alpha-value>)',
      },
      fontFamily: {
        'sans': ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        'display': ['Outfit', 'SF Pro Display', 'Inter', 'sans-serif'],
        'mono': ['JetBrains Mono', 'SF Mono', 'Monaco', 'monospace'],
      },
      fontSize: {
        'xs': ['0.75rem', { lineHeight: '1rem', letterSpacing: '0.05em' }],
        'sm': ['0.875rem', { lineHeight: '1.25rem', letterSpacing: '0.025em' }],
        'base': ['1rem', { lineHeight: '1.5rem', letterSpacing: '0' }],
        'lg': ['1.125rem', { lineHeight: '1.75rem', letterSpacing: '-0.01em' }],
        'xl': ['1.25rem', { lineHeight: '1.75rem', letterSpacing: '-0.02em' }],
        '2xl': ['1.5rem', { lineHeight: '2rem', letterSpacing: '-0.032em' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem', letterSpacing: '-0.035em' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem', letterSpacing: '-0.04em' }],
        '5xl': ['3rem', { lineHeight: '1', letterSpacing: '-0.05em' }],
        '6xl': ['3.75rem', { lineHeight: '1', letterSpacing: '-0.06em' }],
        'huge': ['5rem', { lineHeight: '1', letterSpacing: '-0.07em' }],
        'mega': ['8rem', { lineHeight: '1', letterSpacing: '-0.08em' }],
      },
      spacing: {
        '18': '4.5rem',
        '88': '22rem',
        '128': '32rem',
        '144': '36rem',
      },
      borderRadius: {
        'none': '0',
        'sm': '0.125rem',
        'DEFAULT': '0.5rem',
        'md': '0.5rem',
        'lg': '0.75rem',
        'xl': '1rem',
        '2xl': '1.5rem',
        '3xl': '2rem',
        'full': '9999px',
      },
      boxShadow: {
        'soft': '0 1px 3px 0 rgba(0, 0, 0, 0.05), 0 1px 2px 0 rgba(0, 0, 0, 0.1)',
        'card': '0 4px 6px -1px rgba(0, 0, 0, 0.05), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
        'card-hover': '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
        'modal': '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
        'glass': '0 8px 32px 0 rgba(31, 38, 135, 0.37)',
        'glow': '0 0 20px rgba(0, 70, 255, 0.3)',
        'glow-lg': '0 0 40px rgba(0, 70, 255, 0.4)',
        'primary-glow': '0 0 20px rgba(0, 70, 255, 0.3)',
        'primary-glow-hover': '0 0 30px rgba(0, 70, 255, 0.5)',
        'inner': 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)',
        'neumorphism': '8px 8px 16px #d1d9e6, -8px -8px 16px #ffffff',
        'neumorphism-inset': 'inset 8px 8px 16px #d1d9e6, inset -8px -8px 16px #ffffff',
      },
      backdropBlur: {
        'xs': '2px',
      },
      animation: {
        'fade-in': 'fadeIn 0.3s ease-in-out',
        'fade-out': 'fadeOut 0.3s ease-in-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'slide-down': 'slideDown 0.3s ease-out',
        'slide-left': 'slideLeft 0.3s ease-out',
        'slide-right': 'slideRight 0.3s ease-out',
        'scale-in': 'scaleIn 0.2s ease-out',
        'scale-out': 'scaleOut 0.2s ease-in',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'spin-slow': 'spin 3s linear infinite',
        'bounce-subtle': 'bounceSubtle 2s ease-in-out infinite',
        'shimmer': 'shimmer 2s linear infinite',
        'mesh-glow': 'meshGlow 10s ease-in-out infinite alternate',
      },
      backgroundImage: {
        'public-mesh': "radial-gradient(at 0% 0%, hsla(225,100%,48%,0.15) 0, transparent 50%), radial-gradient(at 50% 0%, hsla(225,100%,48%,0.1) 0, transparent 50%), radial-gradient(at 100% 0%, hsla(225,100%,48%,0.15) 0, transparent 50%)",
        'private-grid': "linear-gradient(to right, rgba(255,255,255,0.02) 1px, transparent 1px), linear-gradient(to bottom, rgba(255,255,255,0.02) 1px, transparent 1px)",
      },
      backgroundSize: {
        'grid-20': '20px 20px',
        'grid-40': '40px 40px',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeOut: {
          '0%': { opacity: '1' },
          '100%': { opacity: '0' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideLeft: {
          '0%': { transform: 'translateX(10px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        slideRight: {
          '0%': { transform: 'translateX(-10px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        scaleOut: {
          '0%': { transform: 'scale(1)', opacity: '1' },
          '100%': { transform: 'scale(0.95)', opacity: '0' },
        },
        bounceSubtle: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-5px)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-1000px 0' },
          '100%': { backgroundPosition: '1000px 0' },
        },
        meshGlow: {
          '0%': { transform: 'scale(1) translate(0, 0)' },
          '100%': { transform: 'scale(1.1) translate(2%, 2%)' },
        },
      },
      transitionDuration: {
        '200': '200ms',
        '300': '300ms',
        '400': '400ms',
        '600': '600ms',
      },
      transitionTimingFunction: {
        'ease-out': 'cubic-bezier(0, 0, 0.2, 1)',
        'ease-in-out': 'cubic-bezier(0.4, 0, 0.2, 1)',
        'bounce-in': 'cubic-bezier(0.68, -0.55, 0.265, 1.55)',
      },
      minHeight: {
        'touch': '44px',
        'screen-safe': '100dvh',
      },
      minWidth: {
        'touch': '44px',
      },
      zIndex: {
        '60': '60',
        '70': '70',
        '80': '80',
        '90': '90',
        '100': '100',
      },
      gridTemplateColumns: {
        'auto-fit': 'repeat(auto-fit, minmax(250px, 1fr))',
        'auto-fill': 'repeat(auto-fill, minmax(250px, 1fr))',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),
    require('tailwindcss-animate'),
  ],
};
